import { ACSArea } from '../types';

export const MEI_ADDON_FLIGHT_ACS: ACSArea[] = [
  {
    area: "",
    tasks: []
  },
  {
    area: "II. Technical Subject Areas",
    tasks: [
      {
        name: "Runway Incursion Avoidance",
        code: "AI.II.C",
        references: "AC 91-73; AIM; Chart Supplements; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25",
        objective: "To determine the applicant understands runway incursion avoidance, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.II.C.K1", category: "K", description: "Runway incursion definition" },
          { code: "AI.II.C.K2", category: "K", description: "Taxi instructions and clearances" },
          { code: "AI.II.C.K3", category: "K", description: "The importance of recording taxi instructions and reviewing taxi routes on the airport diagram" },
          { code: "AI.II.C.K4", category: "K", description: "Airport markings, signs, and lights including the importance of hold lines associated with runways" },
          { code: "AI.II.C.K5", category: "K", description: "Appropriate flight deck activities during taxiing, including taxi route planning, briefing the location of Hot Spots, communicating and coordinating with ATC" },
          { code: "AI.II.C.K6", category: "K", description: "Communication and operational procedures at uncontrolled airports" },
          { code: "AI.II.C.R1", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.II.C.R2", category: "R", description: "Confirmation or expectation bias as related to taxi instructions" },
          { code: "AI.II.C.R3", category: "R", description: "Entering or crossing runways" },
          { code: "AI.II.C.R4", category: "R", description: "Night taxi operations" },
          { code: "AI.II.C.R5", category: "R", description: "Low visibility taxi operations" },
          { code: "AI.II.C.R6", category: "R", description: "Runway incursion after landing" },
          { code: "AI.II.C.R7", category: "R", description: "Operating on taxiways between parallel runways" },
          { code: "AI.II.C.S1", category: "S", description: "Deliver instruction on the elements and techniques for runway incursion avoidance" }
        ]
      },
      {
        name: "Endorsements and Logbook Entries",
        code: "AI.II.K",
        references: "14 CFR part 61; AC 61-65; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25",
        objective: "To determine the applicant understands logbook entries and endorsements, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.II.K.K1", category: "K", description: "Required logbook entries for instruction given" },
          { code: "AI.II.K.K2", category: "K", description: "Required student pilot pre-solo knowledge test, solo endorsements, and logbook entries" },
          { code: "AI.II.K.K3", category: "K", description: "Other required pilot logbook endorsements (e.g., Class B Airspace, SFAR)" },
          { code: "AI.II.K.K4", category: "K", description: "Preparation of a recommendation for a pilot practical test, including appropriate logbook entry and relevant certificate or rating application" },
          { code: "AI.II.K.K4a", category: "K", description: "Initial pilot certification" },
          { code: "AI.II.K.K4b", category: "K", description: "Additional pilot certification" },
          { code: "AI.II.K.K4c", category: "K", description: "Additional aircraft qualification" },
          { code: "AI.II.K.K5", category: "K", description: "Endorsement of a pilot logbook for the satisfactory completion of an FAA flight review" },
          { code: "AI.II.K.K6", category: "K", description: "Required flight instructor records" },
          { code: "AI.II.K.K7", category: "K", description: "Flight instructor renewal and reinstatement requirements" },
          { code: "AI.II.K.R1", category: "R", description: "Endorsements without appropriate limitations or expiration dates" },
          { code: "AI.II.K.S1", category: "S", description: "Describe and prepare logbook entries and endorsements required for at least two of the events specified in the elements or sub-elements of K1 through K5" }
        ]
      },
      {
        name: "One Engine Inoperative (OEI) Performance (AMEL, AMES)",
        code: "AI.II.P",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands elements related to multiengine performance, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.II.P.K1", category: "K", description: "Proficient use of appropriate performance charts, tables, graphs, or other data to determine airplane performance and limitations for all phases of flight" },
          { code: "AI.II.P.K2", category: "K", description: "Effects of exceeding limitations" },
          { code: "AI.II.P.K3", category: "K", description: "Effects of atmospheric conditions on performance" },
          { code: "AI.II.P.K4", category: "K", description: "Factors to be considered to determine required performance is within the airplane's single and multiengine capabilities" },
          { code: "AI.II.P.K5", category: "K", description: "Aerodynamics of OEI operation" },
          { code: "AI.II.P.K5a", category: "K", description: "Critical engine" },
          { code: "AI.II.P.K5b", category: "K", description: "Effects of bank angle on VMC" },
          { code: "AI.II.P.K5c", category: "K", description: "Zero side slip" },
          { code: "AI.II.P.K5d", category: "K", description: "Reasons for loss of directional control" },
          { code: "AI.II.P.K6", category: "K", description: "The relationship between minimum control speed (VMC) and stall speed and the effect of density altitude on that relationship" },
          { code: "AI.II.P.K7", category: "K", description: "How to determine the best course of action after an engine failure" },
          { code: "AI.II.P.R1", category: "R", description: "Exceeding the critical angle of attack" },
          { code: "AI.II.P.R2", category: "R", description: "Loss of directional control" },
          { code: "AI.II.P.R3", category: "R", description: "Flying over terrain that exceeds the single engine service ceiling" },
          { code: "AI.II.P.R4", category: "R", description: "Fuel management" },
          { code: "AI.II.P.S1", category: "S", description: "Compute the expected single engine climb performance" }
        ]
      }
    ]
  },
  {
    area: "V. Preflight Procedures",
    tasks: [
      {
        name: "Preflight Assessment",
        code: "AI.V.A",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-23, FAA-H-8083-25, FAA-H-8083-28; POH/AFM",
        objective: "To determine the applicant understands preflight assessment, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.V.A.K1", category: "K", description: "Pilot self-assessment" },
          { code: "AI.V.A.K2", category: "K", description: "Determining that the airplane to be used is appropriate and airworthy" },
          { code: "AI.V.A.K3", category: "K", description: "Airplane preflight inspection" },
          { code: "AI.V.A.K3a", category: "K", description: "Which items should be inspected" },
          { code: "AI.V.A.K3b", category: "K", description: "The reasons for checking each item" },
          { code: "AI.V.A.K3c", category: "K", description: "How to detect possible defects" },
          { code: "AI.V.A.K3d", category: "K", description: "The associated regulations" },
          { code: "AI.V.A.K4", category: "K", description: "Environmental factors, including weather, terrain, route selection, and obstructions" },
          { code: "AI.V.A.R1", category: "R", description: "Pilot" },
          { code: "AI.V.A.R2", category: "R", description: "Aircraft" },
          { code: "AI.V.A.R3", category: "R", description: "Environment (weather, airports, airspace, terrain, obstacles)" },
          { code: "AI.V.A.R4", category: "R", description: "External pressures" },
          { code: "AI.V.A.R5", category: "R", description: "Aviation security concerns" },
          { code: "AI.V.A.S1", category: "S", description: "Inspect the airplane with reference to an appropriate checklist" },
          { code: "AI.V.A.S2", category: "S", description: "Verify the airplane is in condition for safe flight and conforms to its type design" },
          { code: "AI.V.A.S3", category: "S", description: "Perform self-assessment" },
          { code: "AI.V.A.S4", category: "S", description: "Continue to assess the environment for safe flight" }
        ]
      },
      {
        name: "Flight Deck Management",
        code: "AI.V.B",
        references: "14 CFR part 91; AC 120-71; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-23, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands flight deck management, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.V.B.K1", category: "K", description: "Passenger briefing requirements, including operation and required use of safety restraint systems" },
          { code: "AI.V.B.K2", category: "K", description: "Use of appropriate checklists" },
          { code: "AI.V.B.K3", category: "K", description: "Requirements for current and appropriate navigation data" },
          { code: "AI.V.B.K4", category: "K", description: "Securing items and cargo" },
          { code: "AI.V.B.R1", category: "R", description: "Use of systems or equipment, including automation and portable electronic devices" },
          { code: "AI.V.B.R2", category: "R", description: "Inoperative equipment" },
          { code: "AI.V.B.R3", category: "R", description: "Passenger distractions" },
          { code: "AI.V.B.S1", category: "S", description: "Secure all items in the aircraft" },
          { code: "AI.V.B.S2", category: "S", description: "Conduct an appropriate passenger briefing, including identifying the PIC, use of safety belts, shoulder harnesses, doors, passenger conduct, sterile aircraft, propeller blade avoidance, and emergency procedures" },
          { code: "AI.V.B.S3", category: "S", description: "Properly program and manage the aircraft's automation, as applicable" },
          { code: "AI.V.B.S4", category: "S", description: "Appropriately manage risks by utilizing ADM, including SRM/CRM" }
        ]
      },
      {
        name: "Engine Starting",
        code: "AI.V.C",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-23, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands engine starting, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.V.C.K1", category: "K", description: "Starting under various conditions" },
          { code: "AI.V.C.K2", category: "K", description: "Starting the engines by use of external power" },
          { code: "AI.V.C.K3", category: "K", description: "Engine limitations as they relate to starting" },
          { code: "AI.V.C.R1", category: "R", description: "Propeller safety" },
          { code: "AI.V.C.R2", category: "R", description: "Use of external power unit" },
          { code: "AI.V.C.R3", category: "R", description: "Limitations during starting" },
          { code: "AI.V.C.S1", category: "S", description: "Position the airplane properly considering structures, other aircraft, wind, and the safety of nearby persons and property" },
          { code: "AI.V.C.S2", category: "S", description: "Complete the appropriate checklists" }
        ]
      },
      {
        name: "Taxiing, Airport Signs, and Lighting (ASEL, AMEL)",
        code: "AI.V.D",
        references: "AC 91-73; AIM; Chart Supplements; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands taxiing an airplane, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.V.D.K1", category: "K", description: "Elements of safe taxi operations" },
          { code: "AI.V.D.K2", category: "K", description: "Current airport aeronautical references and information resources such as the Chart Supplement, airport diagram, and NOTAMs" },
          { code: "AI.V.D.K3", category: "K", description: "Taxi instructions and clearances" },
          { code: "AI.V.D.K4", category: "K", description: "Airport markings, signs, and lights" },
          { code: "AI.V.D.K5", category: "K", description: "Visual indicators for wind" },
          { code: "AI.V.D.K6", category: "K", description: "Aircraft lighting, as appropriate" },
          { code: "AI.V.D.K7", category: "K", description: "Procedures for taxi operations" },
          { code: "AI.V.D.K7a", category: "K", description: "Appropriate flight deck activities prior to taxi, including route planning and identifying the location of Hot Spots" },
          { code: "AI.V.D.K7b", category: "K", description: "Radio communications at towered and nontowered airports" },
          { code: "AI.V.D.K7c", category: "K", description: "Entering or crossing runways" },
          { code: "AI.V.D.K7d", category: "K", description: "Night taxi operations" },
          { code: "AI.V.D.K7e", category: "K", description: "Low visibility taxi operations" },
          { code: "AI.V.D.R1", category: "R", description: "Activities and distractions" },
          { code: "AI.V.D.R2", category: "R", description: "Confirmation or expectation bias as related to taxi instructions" },
          { code: "AI.V.D.R3", category: "R", description: "A taxi route or departure runway change" },
          { code: "AI.V.D.R4", category: "R", description: "Runway incursion" },
          { code: "AI.V.D.S1", category: "S", description: "Receive and correctly read back clearances and instructions, if applicable" },
          { code: "AI.V.D.S2", category: "S", description: "Use an airport diagram or taxi chart during taxi, if published, and maintain situational awareness" },
          { code: "AI.V.D.S3", category: "S", description: "Position the flight controls for the existing wind, if applicable" },
          { code: "AI.V.D.S4", category: "S", description: "Complete the appropriate checklists" },
          { code: "AI.V.D.S5", category: "S", description: "Perform a brake check immediately after the airplane begins moving" },
          { code: "AI.V.D.S6", category: "S", description: "Maintain positive control of the airplane during ground operations by controlling direction and speed without excessive use of brakes" },
          { code: "AI.V.D.S7", category: "S", description: "Comply with airport and taxiway markings, signals, and ATC clearances and instructions" },
          { code: "AI.V.D.S8", category: "S", description: "Position the airplane properly relative to hold lines" }
        ]
      },
      {
        name: "Before Takeoff Check",
        code: "AI.V.F",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-23, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands before takeoff checks, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.V.F.K1", category: "K", description: "Purpose of before takeoff checklist items" },
          { code: "AI.V.F.K1a", category: "K", description: "Reasons for checking each item" },
          { code: "AI.V.F.K1b", category: "K", description: "Detecting malfunctions" },
          { code: "AI.V.F.K1c", category: "K", description: "Ensuring the aircraft is in safe operating condition as recommended by the manufacturer" },
          { code: "AI.V.F.R1", category: "R", description: "Division of attention while conducting before takeoff checks" },
          { code: "AI.V.F.R2", category: "R", description: "Unexpected runway changes by ATC" },
          { code: "AI.V.F.R3", category: "R", description: "Wake turbulence" },
          { code: "AI.V.F.R4", category: "R", description: "Potential powerplant failure during takeoff or other malfunction considering operational factors such as airplane characteristics, runway and takeoff path length, surface conditions, environmental conditions, and obstructions" },
          { code: "AI.V.F.S1", category: "S", description: "Review takeoff performance" },
          { code: "AI.V.F.S2", category: "S", description: "Complete the appropriate checklists" },
          { code: "AI.V.F.S3", category: "S", description: "Position the airplane appropriately considering wind direction and the presence of any aircraft, vessels, or buildings as applicable" },
          { code: "AI.V.F.S4", category: "S", description: "Divide attention inside and outside the flight deck" },
          { code: "AI.V.F.S5", category: "S", description: "Verify that engine parameters and airplane configuration are suitable" }
        ]
      }
    ]
  },
  {
    area: "VII. Takeoffs, Landings, and Go-Arounds",
    tasks: [
      {
        name: "Normal Takeoff and Climb",
        code: "AI.VII.A",
        references: "AIM; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands normal takeoff and climb, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.VII.A.K1", category: "K", description: "Procedures for normal and crosswind takeoff" },
          { code: "AI.VII.A.K2", category: "K", description: "Effects of atmospheric conditions including wind on takeoff and climb performance" },
          { code: "AI.VII.A.K3", category: "K", description: "Best angle of climb speed (VX) and best rate of climb speed (VY)" },
          { code: "AI.VII.A.K4", category: "K", description: "Appropriate airplane configuration" },
          { code: "AI.VII.A.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.VII.A.R1", category: "R", description: "Runway selection based on pilot capability, airplane performance, available distance, and wind" },
          { code: "AI.VII.A.R2", category: "R", description: "Effects of crosswind, windshear, tailwind, wake turbulence, and takeoff surface/condition" },
          { code: "AI.VII.A.R3", category: "R", description: "Abnormal operations: rejected takeoff and potential engine failure in takeoff/climb" },
          { code: "AI.VII.A.R4", category: "R", description: "Collision hazards" },
          { code: "AI.VII.A.R5", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.VII.A.R6", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.VII.A.R7", category: "R", description: "Runway incursion" },
          { code: "AI.VII.A.S1", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.VII.A.S2", category: "S", description: "Make radio calls as appropriate" },
          { code: "AI.VII.A.S3", category: "S", description: "Verify assigned/correct runway or takeoff path" },
          { code: "AI.VII.A.S4", category: "S", description: "Determine wind direction with or without visible indicators" },
          { code: "AI.VII.A.S5", category: "S", description: "Position flight controls for the existing wind if applicable" },
          { code: "AI.VII.A.S6", category: "S", description: "Clear the area, taxi into position, and align on runway centerline" },
          { code: "AI.VII.A.S7", category: "S", description: "Advance throttle smoothly to takeoff power and confirm proper engine and flight instrument indications prior to rotation" },
          { code: "AI.VII.A.S8", category: "S", description: "Rotate and lift off at recommended airspeed and accelerate to VY" },
          { code: "AI.VII.A.S9", category: "S", description: "Maintain pitch for VY ±5 kts to a safe maneuvering altitude" },
          { code: "AI.VII.A.S10", category: "S", description: "Configure airplane per manufacturer's guidance" },
          { code: "AI.VII.A.S11", category: "S", description: "Maintain directional control and proper wind-drift correction throughout takeoff and climb" },
          { code: "AI.VII.A.S12", category: "S", description: "Comply with noise abatement procedures as applicable" },
          { code: "AI.VII.A.S13", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Normal Approach and Landing",
        code: "AI.VII.B",
        references: "AIM; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands normal approach and landing, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.VII.B.K1", category: "K", description: "Procedures for normal and crosswind approach and landing" },
          { code: "AI.VII.B.K2", category: "K", description: "Stabilized approach including energy management concepts" },
          { code: "AI.VII.B.K3", category: "K", description: "Effects of atmospheric conditions including wind on approach and landing performance" },
          { code: "AI.VII.B.K4", category: "K", description: "Wind correction techniques on approach and landing" },
          { code: "AI.VII.B.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.VII.B.R1", category: "R", description: "Runway/surface selection based on pilot capability, aircraft performance, available distance, and wind" },
          { code: "AI.VII.B.R2", category: "R", description: "Effects of crosswind, windshear, tailwind, wake turbulence, and landing surface/condition" },
          { code: "AI.VII.B.R3", category: "R", description: "Planning for rejected landing/go-around and LAHSO" },
          { code: "AI.VII.B.R4", category: "R", description: "Collision hazards" },
          { code: "AI.VII.B.R5", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.VII.B.R6", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.VII.B.S1", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.VII.B.S2", category: "S", description: "Make radio calls as appropriate" },
          { code: "AI.VII.B.S3", category: "S", description: "Ensure airplane is aligned with the correct/assigned runway" },
          { code: "AI.VII.B.S4", category: "S", description: "Scan runway and adjoining area for traffic and obstructions" },
          { code: "AI.VII.B.S5", category: "S", description: "Select and aim for suitable touchdown point considering wind, surface, and obstructions" },
          { code: "AI.VII.B.S6", category: "S", description: "Establish recommended approach configuration, airspeed, and trim; adjust pitch and power to maintain stabilized approach" },
          { code: "AI.VII.B.S7", category: "S", description: "Maintain published approach airspeed or 1.3 VSO ±5 kts with gust factor applied" },
          { code: "AI.VII.B.S8", category: "S", description: "Maintain directional control and crosswind correction throughout approach and landing" },
          { code: "AI.VII.B.S9", category: "S", description: "Make smooth, timely, and correct control inputs during round out and touchdown" },
          { code: "AI.VII.B.S10", category: "S", description: "Touch down within 200 ft of specified point with no side drift and longitudinal axis aligned over centerline" },
          { code: "AI.VII.B.S11", category: "S", description: "Execute timely go-around if approach cannot be made within tolerances or conditions are unsafe" },
          { code: "AI.VII.B.S12", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Short-Field Takeoff and Maximum Performance Climb (ASEL, AMEL)",
        code: "AI.VII.E",
        references: "AIM; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands short-field takeoff and maximum performance climb, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.VII.E.K1", category: "K", description: "Purpose of and procedures for short-field takeoff and maximum performance climb" },
          { code: "AI.VII.E.K2", category: "K", description: "Effects of atmospheric conditions including wind on takeoff and climb performance" },
          { code: "AI.VII.E.K3", category: "K", description: "Best angle of climb speed (VX) and best rate of climb speed (VY)" },
          { code: "AI.VII.E.K4", category: "K", description: "Appropriate airplane configuration" },
          { code: "AI.VII.E.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.VII.E.R1", category: "R", description: "Runway selection based on pilot capability, airplane performance, available distance, and wind" },
          { code: "AI.VII.E.R2", category: "R", description: "Effects of crosswind, windshear, tailwind, wake turbulence, and surface/condition" },
          { code: "AI.VII.E.R3", category: "R", description: "Abnormal operations: rejected takeoff and potential engine failure in takeoff/climb" },
          { code: "AI.VII.E.R4", category: "R", description: "Collision hazards" },
          { code: "AI.VII.E.R5", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.VII.E.R6", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.VII.E.S1", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.VII.E.S2", category: "S", description: "Make radio calls as appropriate" },
          { code: "AI.VII.E.S3", category: "S", description: "Verify assigned/correct runway" },
          { code: "AI.VII.E.S4", category: "S", description: "Determine wind direction with or without visible indicators" },
          { code: "AI.VII.E.S5", category: "S", description: "Position flight controls for existing wind if applicable" },
          { code: "AI.VII.E.S6", category: "S", description: "Align on centerline utilizing maximum available takeoff area" },
          { code: "AI.VII.E.S7", category: "S", description: "Apply brakes while setting engine power to achieve maximum performance; confirm prior to brake release" },
          { code: "AI.VII.E.S8", category: "S", description: "Rotate at recommended airspeed and accelerate to obstacle clearance airspeed or VX ±5 kts" },
          { code: "AI.VII.E.S9", category: "S", description: "Maintain obstacle clearance airspeed or VX ±5 kts until obstacle is cleared or 50 ft AGL" },
          { code: "AI.VII.E.S10", category: "S", description: "Transition to VY ±5 kts after clearing obstacle; configure per manufacturer's guidance" },
          { code: "AI.VII.E.S11", category: "S", description: "Maintain VY ±5 kts to safe maneuvering altitude" },
          { code: "AI.VII.E.S12", category: "S", description: "Maintain directional control and proper wind-drift correction throughout takeoff and climb" },
          { code: "AI.VII.E.S13", category: "S", description: "Comply with noise abatement procedures as applicable" },
          { code: "AI.VII.E.S14", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Short-Field Approach and Landing (ASEL, AMEL)",
        code: "AI.VII.F",
        references: "AIM; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands short-field approach and landing, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.VII.F.K1", category: "K", description: "Purpose of and procedures for short-field approach and landing" },
          { code: "AI.VII.F.K2", category: "K", description: "Stabilized approach including energy management concepts" },
          { code: "AI.VII.F.K3", category: "K", description: "Effects of atmospheric conditions including wind on approach and landing performance" },
          { code: "AI.VII.F.K4", category: "K", description: "Wind correction techniques on approach and landing" },
          { code: "AI.VII.F.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.VII.F.R1", category: "R", description: "Runway selection based on pilot capability, airplane performance, available distance, and wind" },
          { code: "AI.VII.F.R2", category: "R", description: "Effects of crosswind, windshear, tailwind, wake turbulence, and surface/condition" },
          { code: "AI.VII.F.R3", category: "R", description: "Planning for rejected landing/go-around and LAHSO" },
          { code: "AI.VII.F.R4", category: "R", description: "Collision hazards" },
          { code: "AI.VII.F.R5", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.VII.F.R6", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.VII.F.S1", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.VII.F.S2", category: "S", description: "Make radio calls as appropriate" },
          { code: "AI.VII.F.S3", category: "S", description: "Ensure airplane is aligned with the correct/assigned runway" },
          { code: "AI.VII.F.S4", category: "S", description: "Scan landing runway and adjoining area for traffic and obstructions" },
          { code: "AI.VII.F.S5", category: "S", description: "Select and aim for suitable touchdown point considering wind, surface, and obstructions" },
          { code: "AI.VII.F.S6", category: "S", description: "Establish recommended approach configuration, airspeed, and trim; adjust to maintain stabilized approach" },
          { code: "AI.VII.F.S7", category: "S", description: "Maintain published approach airspeed or 1.3 VSO ±5 kts with gust factor applied" },
          { code: "AI.VII.F.S8", category: "S", description: "Maintain directional control and crosswind correction throughout approach and landing" },
          { code: "AI.VII.F.S9", category: "S", description: "Smooth, timely, and correct control inputs before, during, and after touchdown" },
          { code: "AI.VII.F.S10", category: "S", description: "Touch down within 100 ft of specified point, no side drift, minimum float, longitudinal axis aligned with centerline" },
          { code: "AI.VII.F.S11", category: "S", description: "Use manufacturer's recommended procedures for configuration and braking" },
          { code: "AI.VII.F.S12", category: "S", description: "Execute timely go-around if approach cannot be made within tolerances or conditions are unsafe" },
          { code: "AI.VII.F.S13", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Go-Around/Rejected Landing",
        code: "AI.VII.N",
        references: "AIM; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands go-around/rejected landing with emphasis on factors that contribute to conditions requiring a go-around, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.VII.N.K1", category: "K", description: "Purpose of and procedures for go-around or rejected landing" },
          { code: "AI.VII.N.K2", category: "K", description: "Stabilized approach including energy management concepts" },
          { code: "AI.VII.N.K3", category: "K", description: "Effects of atmospheric conditions including wind and density altitude on a go-around" },
          { code: "AI.VII.N.K4", category: "K", description: "Wind correction techniques on takeoff/departure and approach/landing" },
          { code: "AI.VII.N.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.VII.N.R1", category: "R", description: "Delayed recognition of need for go-around/rejected landing" },
          { code: "AI.VII.N.R2", category: "R", description: "Delayed performance of go-around at low altitude" },
          { code: "AI.VII.N.R3", category: "R", description: "Power application" },
          { code: "AI.VII.N.R4", category: "R", description: "Configuring the airplane" },
          { code: "AI.VII.N.R5", category: "R", description: "Collision hazards" },
          { code: "AI.VII.N.R6", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.VII.N.R7", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.VII.N.R8", category: "R", description: "Managing go-around after accepting a LAHSO clearance" },
          { code: "AI.VII.N.R9", category: "R", description: "Runway incursion" },
          { code: "AI.VII.N.S1", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.VII.N.S2", category: "S", description: "Make radio calls as appropriate" },
          { code: "AI.VII.N.S3", category: "S", description: "Make timely decision to discontinue the approach to landing" },
          { code: "AI.VII.N.S4", category: "S", description: "Apply takeoff power immediately and transition to VX or VY ±5 kts as appropriate" },
          { code: "AI.VII.N.S5", category: "S", description: "Configure airplane after positive rate of climb verified per manufacturer's instructions" },
          { code: "AI.VII.N.S6", category: "S", description: "Maneuver to side of runway when necessary to clear conflicting traffic" },
          { code: "AI.VII.N.S7", category: "S", description: "Maintain VY ±5 kts to safe maneuvering altitude" },
          { code: "AI.VII.N.S8", category: "S", description: "Maintain directional control and proper wind-drift correction throughout climb" },
          { code: "AI.VII.N.S9", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      }
    ]
  },
  {
    area: "IX. Performance and Ground Reference Maneuvers",
    tasks: [
      {
        name: "Steep Turns",
        code: "AI.IX.A",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands steep turns, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.IX.A.K1", category: "K", description: "Purpose of and procedures for steep turns" },
          { code: "AI.IX.A.K2", category: "K", description: "Pilot sensations and control forces" },
          { code: "AI.IX.A.K3", category: "K", description: "Aerodynamics of steep turns: coordinated flight, overbanking tendencies, maneuvering speed/weight changes, load factor/accelerated stalls, rate and radius of turn" },
          { code: "AI.IX.A.K4", category: "K", description: "Common errors related to this Task" },
          { code: "AI.IX.A.R1", category: "R", description: "Division of attention between aircraft control and orientation" },
          { code: "AI.IX.A.R2", category: "R", description: "Collision hazards" },
          { code: "AI.IX.A.R3", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.IX.A.R4", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.IX.A.R5", category: "R", description: "Uncoordinated flight" },
          { code: "AI.IX.A.S1", category: "S", description: "Clear the area" },
          { code: "AI.IX.A.S2", category: "S", description: "Establish manufacturer's recommended airspeed or not to exceed VA" },
          { code: "AI.IX.A.S3", category: "S", description: "Roll into coordinated 360° steep turn with approximately 50° bank" },
          { code: "AI.IX.A.S4", category: "S", description: "Perform the Task in the opposite direction" },
          { code: "AI.IX.A.S5", category: "S", description: "Maintain entry altitude ±100 ft, airspeed ±10 kts, bank ±5°, roll out on entry heading ±10°" },
          { code: "AI.IX.A.S6", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      }
    ]
  },
  {
    area: "X. Slow Flight, Stalls, and Spins",
    tasks: [
      {
        name: "Maneuvering During Slow Flight",
        code: "AI.X.A",
        references: "AC 61-67; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands maneuvering during slow flight in cruise configuration, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.X.A.K1", category: "K", description: "Purpose of and procedures for proper slow flight" },
          { code: "AI.X.A.K2", category: "K", description: "Aerodynamics of slow flight in various configurations: AOA, airspeed, load factor, power, weight, CG, attitude, and yaw effects" },
          { code: "AI.X.A.K3", category: "K", description: "Common errors related to this Task" },
          { code: "AI.X.A.R1", category: "R", description: "Inadvertent slow flight and flight with stall warning leading to loss of control" },
          { code: "AI.X.A.R2", category: "R", description: "Range and limitations of stall warning indicators (buffet, stall horn, etc.)" },
          { code: "AI.X.A.R3", category: "R", description: "Uncoordinated flight" },
          { code: "AI.X.A.R4", category: "R", description: "Effect of environmental elements on performance (turbulence, microbursts, high density altitude)" },
          { code: "AI.X.A.R5", category: "R", description: "Collision hazards" },
          { code: "AI.X.A.R6", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.X.A.S1", category: "S", description: "Clear the area" },
          { code: "AI.X.A.S2", category: "S", description: "Select entry altitude allowing Task completion no lower than 1,500 ft AGL (ASEL/ASES) or 3,000 ft AGL (AMEL/AMES)" },
          { code: "AI.X.A.S3", category: "S", description: "Establish and maintain airspeed at which any further AOA increase, load factor increase, or power reduction would cause stall warning" },
          { code: "AI.X.A.S4", category: "S", description: "Accomplish coordinated straight-and-level, turns, climbs, and descents in evaluator-specified configuration without stall warning" },
          { code: "AI.X.A.S5", category: "S", description: "Maintain altitude ±50 ft, heading ±10°, airspeed +5/-0 kts, bank angle ±5°" },
          { code: "AI.X.A.S6", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Power-Off Stalls",
        code: "AI.X.C",
        references: "AC 61-67; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands power-off stalls, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.X.C.K1", category: "K", description: "Purpose of and procedures for power-off stalls" },
          { code: "AI.X.C.K2", category: "K", description: "Stall aerodynamics in various configurations: AOA, airspeed, load factor, power, weight, CG, attitude, yaw" },
          { code: "AI.X.C.K3", category: "K", description: "Stall characteristics related to airplane design; recognizing impending and full stall by sight, sound, or feel" },
          { code: "AI.X.C.K4", category: "K", description: "Factors and situations leading to power-off stall and prevention actions" },
          { code: "AI.X.C.K5", category: "K", description: "Fundamentals of stall recovery" },
          { code: "AI.X.C.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.X.C.R1", category: "R", description: "Factors and situations leading to inadvertent power-off stall, spin, and loss of control" },
          { code: "AI.X.C.R2", category: "R", description: "Range and limitations of stall warning indicators" },
          { code: "AI.X.C.R3", category: "R", description: "Stall warnings during normal operations" },
          { code: "AI.X.C.R4", category: "R", description: "Stall recovery procedure" },
          { code: "AI.X.C.R5", category: "R", description: "Secondary stalls, accelerated stalls, and cross-control stalls" },
          { code: "AI.X.C.R6", category: "R", description: "Effect of environmental elements on performance related to power-off stalls" },
          { code: "AI.X.C.R7", category: "R", description: "Collision hazards" },
          { code: "AI.X.C.R8", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.X.C.S1", category: "S", description: "Clear the area" },
          { code: "AI.X.C.S2", category: "S", description: "Select entry altitude allowing Task completion no lower than 1,500 ft AGL (ASEL/ASES) or 3,000 ft AGL (AMEL/AMES)" },
          { code: "AI.X.C.S3", category: "S", description: "Configure in approach or landing configuration as specified; maintain coordinated flight" },
          { code: "AI.X.C.S4", category: "S", description: "Establish a stabilized descent" },
          { code: "AI.X.C.S5", category: "S", description: "Transition smoothly from approach/landing attitude to pitch that induces stall" },
          { code: "AI.X.C.S6", category: "S", description: "Maintain heading ±10° (straight) or bank not exceeding 20° ±5° (turning) until impending or full stall as specified" },
          { code: "AI.X.C.S7", category: "S", description: "Acknowledge cues at first indication of stall (buffet, stall horn, etc.)" },
          { code: "AI.X.C.S8", category: "S", description: "Recover at first indication or full stall as specified by evaluator" },
          { code: "AI.X.C.S9", category: "S", description: "Configure per manufacturer's guidance; accelerate to VX or VY" },
          { code: "AI.X.C.S10", category: "S", description: "Return to altitude, heading, and airspeed specified by evaluator" },
          { code: "AI.X.C.S11", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Power-On Stalls",
        code: "AI.X.D",
        references: "AC 61-67; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands power-on stalls, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.X.D.K1", category: "K", description: "Purpose of and procedures for power-on stalls" },
          { code: "AI.X.D.K2", category: "K", description: "Stall aerodynamics in various configurations: AOA, airspeed, load factor, power, weight, CG, attitude, yaw" },
          { code: "AI.X.D.K3", category: "K", description: "Stall characteristics related to airplane design; recognizing impending and full stall by sight, sound, or feel" },
          { code: "AI.X.D.K4", category: "K", description: "Factors and situations leading to power-on stall and prevention actions" },
          { code: "AI.X.D.K5", category: "K", description: "Fundamentals of stall recovery" },
          { code: "AI.X.D.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.X.D.R1", category: "R", description: "Factors and situations leading to inadvertent power-on stall, spin, and loss of control" },
          { code: "AI.X.D.R2", category: "R", description: "Range and limitations of stall warning indicators" },
          { code: "AI.X.D.R3", category: "R", description: "Stall warnings during normal operations" },
          { code: "AI.X.D.R4", category: "R", description: "Stall recovery procedure" },
          { code: "AI.X.D.R5", category: "R", description: "Secondary stalls, accelerated stalls, elevator trim stalls, and cross-control stalls" },
          { code: "AI.X.D.R6", category: "R", description: "Effect of environmental elements on performance related to power-on stalls" },
          { code: "AI.X.D.R7", category: "R", description: "Collision hazards" },
          { code: "AI.X.D.R8", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.X.D.S1", category: "S", description: "Clear the area" },
          { code: "AI.X.D.S2", category: "S", description: "Select entry altitude allowing Task completion no lower than 1,500 ft AGL (ASEL/ASES) or 3,000 ft AGL (AMEL/AMES)" },
          { code: "AI.X.D.S3", category: "S", description: "Establish takeoff, departure, or cruise configuration as specified; maintain coordinated flight" },
          { code: "AI.X.D.S4", category: "S", description: "Set power to no less than 65 percent" },
          { code: "AI.X.D.S5", category: "S", description: "Transition smoothly from takeoff/departure attitude to pitch that induces stall" },
          { code: "AI.X.D.S6", category: "S", description: "Maintain heading ±10° (straight) or bank not exceeding 20° ±10° (turning) until impending or full stall as specified" },
          { code: "AI.X.D.S7", category: "S", description: "Acknowledge cues at first indication of stall (buffet, stall horn, etc.)" },
          { code: "AI.X.D.S8", category: "S", description: "Recover at first indication or full stall as specified by evaluator" },
          { code: "AI.X.D.S9", category: "S", description: "Configure per manufacturer's guidance; accelerate to VX or VY" },
          { code: "AI.X.D.S10", category: "S", description: "Return to altitude, heading, and airspeed specified by evaluator" },
          { code: "AI.X.D.S11", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Accelerated Stalls",
        code: "AI.X.E",
        references: "AC 61-67; FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands accelerated stalls (power-on and power-off), can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.X.E.K1", category: "K", description: "Purpose of and procedures for accelerated stalls" },
          { code: "AI.X.E.K2", category: "K", description: "Aerodynamics of accelerated stalls in various configurations: AOA, airspeed, load factor, power, weight, CG, attitude, yaw" },
          { code: "AI.X.E.K3", category: "K", description: "Stall characteristics related to airplane design; recognizing impending and full stall by sight, sound, or feel" },
          { code: "AI.X.E.K4", category: "K", description: "Factors leading to accelerated stall and prevention actions" },
          { code: "AI.X.E.K5", category: "K", description: "Fundamentals of stall recovery" },
          { code: "AI.X.E.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.X.E.R1", category: "R", description: "Factors and situations leading to inadvertent accelerated stall, spin, and loss of control" },
          { code: "AI.X.E.R2", category: "R", description: "Range and limitations of stall warning indicators" },
          { code: "AI.X.E.R3", category: "R", description: "Stall warnings during normal operations" },
          { code: "AI.X.E.R4", category: "R", description: "Stall recovery procedure" },
          { code: "AI.X.E.R5", category: "R", description: "Secondary stalls, cross-control stalls, and spins" },
          { code: "AI.X.E.R6", category: "R", description: "Effect of environmental elements on performance related to accelerated stalls" },
          { code: "AI.X.E.R7", category: "R", description: "Collision hazards" },
          { code: "AI.X.E.R8", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.X.E.S1", category: "S", description: "Clear the area" },
          { code: "AI.X.E.S2", category: "S", description: "Select entry altitude allowing Task completion no lower than 3,000 ft AGL" },
          { code: "AI.X.E.S3", category: "S", description: "Establish configuration as specified by evaluator" },
          { code: "AI.X.E.S4", category: "S", description: "Set appropriate power so airspeed does not exceed VA or any other POH/AFM limitation" },
          { code: "AI.X.E.S5", category: "S", description: "Establish and maintain coordinated turn at 45° bank; increase elevator back pressure smoothly until impending stall" },
          { code: "AI.X.E.S6", category: "S", description: "Acknowledge cues at first indication of stall (buffet, stall horn, etc.)" },
          { code: "AI.X.E.S7", category: "S", description: "Execute stall recovery per POH/FM procedures" },
          { code: "AI.X.E.S8", category: "S", description: "Configure per manufacturer's guidance; accelerate to VX or VY" },
          { code: "AI.X.E.S9", category: "S", description: "Return to altitude, heading, and airspeed specified by evaluator" },
          { code: "AI.X.E.S10", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },

    ]
  },
  {
    area: "XII. Emergency Operations",
    tasks: [
      {
        name: "Emergency Descent",
        code: "AI.XII.A",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands emergency descent, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.A.K1", category: "K", description: "Purpose of and procedures for emergency descent" },
          { code: "AI.XII.A.K2", category: "K", description: "Situations requiring emergency descent (depressurization, smoke, engine fire)" },
          { code: "AI.XII.A.K3", category: "K", description: "Immediate action items and emergency procedures" },
          { code: "AI.XII.A.K4", category: "K", description: "Aircraft performance and limitations" },
          { code: "AI.XII.A.K5", category: "K", description: "Airspeed including airspeed limitations" },
          { code: "AI.XII.A.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.A.R1", category: "R", description: "Altitude, wind, terrain, obstructions, gliding distance, and available landing distance" },
          { code: "AI.XII.A.R2", category: "R", description: "Collision hazards" },
          { code: "AI.XII.A.R3", category: "R", description: "Configuring the airplane" },
          { code: "AI.XII.A.R4", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.XII.A.S1", category: "S", description: "Clear the area" },
          { code: "AI.XII.A.S2", category: "S", description: "Establish and maintain appropriate airspeed and configuration per POH/AFM for the emergency scenario" },
          { code: "AI.XII.A.S3", category: "S", description: "Maintain orientation, divide attention appropriately, and plan and execute a smooth recovery" },
          { code: "AI.XII.A.S4", category: "S", description: "Use bank angle between 30° and 45° to maintain positive load factors during descent" },
          { code: "AI.XII.A.S5", category: "S", description: "Maintain airspeed +0/-10 kts; level off at specified altitude ±100 ft" },
          { code: "AI.XII.A.S6", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.XII.A.S7", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Systems and Equipment Malfunctions",
        code: "AI.XII.C",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands system and equipment malfunctions appropriate to the aircraft, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.C.K1", category: "K", description: "Causes of partial or complete power loss related to the specific powerplant(s)" },
          { code: "AI.XII.C.K2", category: "K", description: "System and equipment malfunctions: electrical, vacuum/pressure/instruments, pitot-static, EFD, landing gear/flaps, inoperative trim" },
          { code: "AI.XII.C.K3", category: "K", description: "Causes and remedies for smoke or fire onboard" },
          { code: "AI.XII.C.K4", category: "K", description: "Other systems specific to the aircraft (supplemental oxygen, deicing)" },
          { code: "AI.XII.C.K5", category: "K", description: "Inadvertent door or window opening" },
          { code: "AI.XII.C.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.C.R1", category: "R", description: "Startle response" },
          { code: "AI.XII.C.R2", category: "R", description: "Checklist usage for a system or equipment malfunction" },
          { code: "AI.XII.C.R3", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.XII.C.R4", category: "R", description: "Undesired aircraft state" },
          { code: "AI.XII.C.S1", category: "S", description: "Determine appropriate action for simulated emergencies from at least three elements/sub-elements in K1–K5" },
          { code: "AI.XII.C.S2", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.XII.C.S3", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Emergency Equipment and Survival Gear",
        code: "AI.XII.D",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands emergency equipment and survival gear, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.D.K1", category: "K", description: "ELT operations, limitations, and testing requirements" },
          { code: "AI.XII.D.K2", category: "K", description: "Fire extinguisher operations and limitations" },
          { code: "AI.XII.D.K3", category: "K", description: "Emergency equipment and survival gear for climate extremes, mountainous terrain, and overwater operations" },
          { code: "AI.XII.D.K4", category: "K", description: "When to deploy ballistic parachute and passenger briefing if equipped" },
          { code: "AI.XII.D.K5", category: "K", description: "When to activate emergency auto-land system and brief passengers if equipped" },
          { code: "AI.XII.D.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.D.R1", category: "R", description: "Survival gear (water, clothing, shelter) for 48 to 72 hours" },
          { code: "AI.XII.D.R2", category: "R", description: "Use of a ballistic parachute system" },
          { code: "AI.XII.D.R3", category: "R", description: "Use of emergency auto-land system if installed" },
          { code: "AI.XII.D.S1", category: "S", description: "Identify appropriate equipment and personal gear" },
          { code: "AI.XII.D.S2", category: "S", description: "Brief passengers on proper use of on-board emergency equipment and survival gear" },
          { code: "AI.XII.D.S3", category: "S", description: "Simulate ballistic parachute deployment procedures if equipped" },
          { code: "AI.XII.D.S4", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Engine Failure During Takeoff Before VMC (Simulated) (AMEL, AMES)",
        code: "AI.XII.E",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands engine failure during takeoff before VMC, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.E.K1", category: "K", description: "Factors affecting minimum controllable speed (VMC)" },
          { code: "AI.XII.E.K2", category: "K", description: "VMC red line, VYSE blue line, and safe single-engine speed (VSSE)" },
          { code: "AI.XII.E.K3", category: "K", description: "Accelerate-stop and accelerate-go distances" },
          { code: "AI.XII.E.K4", category: "K", description: "How to identify, verify, feather, and secure an inoperative engine" },
          { code: "AI.XII.E.K5", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.E.R1", category: "R", description: "Potential engine failure during takeoff" },
          { code: "AI.XII.E.R2", category: "R", description: "Collision hazards" },
          { code: "AI.XII.E.R3", category: "R", description: "Configuring the airplane" },
          { code: "AI.XII.E.R4", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.XII.E.S1", category: "S", description: "Promptly recognize engine failure, maintain directional control, and apply brakes as necessary" },
          { code: "AI.XII.E.S2", category: "S", description: "Maintain directional control and apply brakes (AMEL) or flight controls (AMES) as necessary" },
          { code: "AI.XII.E.S3", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Engine Failure After Liftoff (Simulated) (AMEL, AMES)",
        code: "AI.XII.F",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands engine failure after liftoff, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.F.K1", category: "K", description: "Factors affecting minimum controllable speed (VMC)" },
          { code: "AI.XII.F.K2", category: "K", description: "VMC red line, VYSE blue line, and safe single-engine speed (VSSE)" },
          { code: "AI.XII.F.K3", category: "K", description: "Accelerate-stop and accelerate-go distances" },
          { code: "AI.XII.F.K4", category: "K", description: "How to identify, verify, feather, and secure an inoperative engine" },
          { code: "AI.XII.F.K5", category: "K", description: "Importance of drag reduction including propeller feathering, gear and flap retraction, the manufacturer's recommended control input, and its relation to zero sideslip" },
          { code: "AI.XII.F.K6", category: "K", description: "Simulated propeller feathering and the evaluator's zero-thrust procedures and responsibilities" },
          { code: "AI.XII.F.K7", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.F.R1", category: "R", description: "Potential engine failure after liftoff" },
          { code: "AI.XII.F.R2", category: "R", description: "Collision hazards" },
          { code: "AI.XII.F.R3", category: "R", description: "Configuring the airplane" },
          { code: "AI.XII.F.R4", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.XII.F.R5", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.XII.F.S1", category: "S", description: "Promptly recognize engine failure, maintain control, and use appropriate emergency procedures" },
          { code: "AI.XII.F.S2", category: "S", description: "Establish VYSE; if obstructions are present, establish VXSE or VMC + 5 knots, whichever is greater, until obstructions are cleared, then transition to VYSE" },
          { code: "AI.XII.F.S3", category: "S", description: "Reduce drag by retracting landing gear and flaps in accordance with manufacturer's guidance" },
          { code: "AI.XII.F.S4", category: "S", description: "Simulate feathering the propeller on the inoperative engine" },
          { code: "AI.XII.F.S5", category: "S", description: "Use flight controls in the proper combination as recommended by the manufacturer and trim as required" },
          { code: "AI.XII.F.S6", category: "S", description: "Monitor the operating engine and aircraft systems and make adjustments as necessary" },
          { code: "AI.XII.F.S7", category: "S", description: "Recognize the airplane's performance capabilities and if a climb is not possible, maintain VYSE and return to the departure airport or initiate an approach to the most suitable landing area" },
          { code: "AI.XII.F.S8", category: "S", description: "Simulate securing the inoperative engine" },
          { code: "AI.XII.F.S9", category: "S", description: "Maintain heading ±10° and airspeed ±5 knots" },
          { code: "AI.XII.F.S10", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.XII.F.S11", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      },
      {
        name: "Approach and Landing with an Inoperative Engine (Simulated) (AMEL, AMES)",
        code: "AI.XII.G",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; POH/AFM",
        objective: "To determine the applicant understands approach and landing with an inoperative engine, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XII.G.K1", category: "K", description: "Factors affecting minimum controllable speed (VMC)" },
          { code: "AI.XII.G.K2", category: "K", description: "VMC red line and VYSE blue line" },
          { code: "AI.XII.G.K3", category: "K", description: "How to identify, verify, feather, and secure an inoperative engine" },
          { code: "AI.XII.G.K4", category: "K", description: "Importance of drag reduction including propeller feathering, gear and flap retraction, and its relation to zero sideslip" },
          { code: "AI.XII.G.K5", category: "K", description: "Applicant responsibilities during simulated feathering" },
          { code: "AI.XII.G.K6", category: "K", description: "Common errors related to this Task" },
          { code: "AI.XII.G.R1", category: "R", description: "Potential engine failure in flight or during an approach" },
          { code: "AI.XII.G.R2", category: "R", description: "Collision hazards" },
          { code: "AI.XII.G.R3", category: "R", description: "Configuring the airplane" },
          { code: "AI.XII.G.R4", category: "R", description: "Low altitude maneuvering including stall, spin, or CFIT" },
          { code: "AI.XII.G.R5", category: "R", description: "Distractions, task prioritization, loss of situational awareness, or disorientation" },
          { code: "AI.XII.G.R6", category: "R", description: "Possible single-engine go-around" },
          { code: "AI.XII.G.S1", category: "S", description: "Promptly recognize engine failure and maintain positive aircraft control" },
          { code: "AI.XII.G.S2", category: "S", description: "Set engine controls, reduce drag, identify and verify the inoperative engine, and simulate feathering of the propeller" },
          { code: "AI.XII.G.S3", category: "S", description: "Follow manufacturer's recommended emergency procedures and complete the appropriate checklist" },
          { code: "AI.XII.G.S4", category: "S", description: "Monitor the operating engine and aircraft systems and make adjustments as necessary" },
          { code: "AI.XII.G.S5", category: "S", description: "Maintain manufacturer's recommended approach airspeed ±5 knots in landing configuration with a stabilized approach until landing is assured" },
          { code: "AI.XII.G.S6", category: "S", description: "Make smooth, timely, and correct control application before, during, and after touchdown" },
          { code: "AI.XII.G.S7", category: "S", description: "Touch down on the first one-third of available runway with no drift and longitudinal axis aligned with centerline" },
          { code: "AI.XII.G.S8", category: "S", description: "Maintain directional control and appropriate crosswind correction throughout approach and landing" },
          { code: "AI.XII.G.S9", category: "S", description: "Complete the appropriate checklist(s)" },
          { code: "AI.XII.G.S10", category: "S", description: "Analyze and correct common errors related to this Task" }
        ]
      }
    ]
  },
  {
    area: "XIII. Multiengine Operations",
    tasks: [
      {
        name: "Maneuvering with One Engine Inoperative (AMEL, AMES)",
        code: "AI.XIII.A",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands one engine inoperative, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XIII.A.K1", category: "K", description: "Factors affecting minimum controllable speed VMC." },
          { code: "AI.XIII.A.K2", category: "K", description: "VMC red line and VYSE blue line." },
          { code: "AI.XIII.A.K3", category: "K", description: "How to identify verify feather and secure an inoperative engine." },
          { code: "AI.XIII.A.K4", category: "K", description: "Importance of drag reduction including propeller feathering gear and flap retraction the manufacturer's recommended control input and its relation to zero sideslip." },
          { code: "AI.XIII.A.K5", category: "K", description: "Feathering securing unfeathering and restarting." },
          { code: "AI.XIII.A.K6", category: "K", description: "Common errors related to this Task." },
          { code: "AI.XIII.A.R1", category: "R", description: "Potential engine failure during flight." },
          { code: "AI.XIII.A.R2", category: "R", description: "Collision hazards." },
          { code: "AI.XIII.A.R3", category: "R", description: "Configuring the airplane." },
          { code: "AI.XIII.A.R4", category: "R", description: "Low altitude maneuvering including stall spin or CFIT." },
          { code: "AI.XIII.A.R5", category: "R", description: "Distractions task prioritization loss of situational awareness or disorientation." },
          { code: "AI.XIII.A.S1", category: "S", description: "Recognize engine failure maintain control use manufacturer's memory item procedures and use appropriate emergency procedures." },
          { code: "AI.XIII.A.S2", category: "S", description: "Set engine controls identify and verify the inoperative engine and feather the appropriate propeller." },
          { code: "AI.XIII.A.S3", category: "S", description: "Use flight controls in the proper combination as recommended by the manufacturer and trim as required." },
          { code: "AI.XIII.A.S4", category: "S", description: "Attempt to determine and resolve the reason for the engine failure." },
          { code: "AI.XIII.A.S5", category: "S", description: "Secure the inoperative engine and monitor the operating engine and make necessary adjustments." },
          { code: "AI.XIII.A.S6", category: "S", description: "Restart the inoperative engine using manufacturer's restart procedures." },
          { code: "AI.XIII.A.S7", category: "S", description: "Maintain altitude plus or minus 100 feet or minimum sink rate if applicable airspeed plus or minus 10 knots and selected headings plus or minus 10 degrees." },
          { code: "AI.XIII.A.S8", category: "S", description: "Complete the appropriate checklists." },
          { code: "AI.XIII.A.S9", category: "S", description: "Analyze and correct common errors related to this Task." }
        ]
      },
      {
        name: "VMC Demonstration (AMEL, AMES)",
        code: "AI.XIII.B",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands VMC demonstration, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XIII.B.K1", category: "K", description: "Purpose of the maneuver." },
          { code: "AI.XIII.B.K2", category: "K", description: "Proper procedures for maneuver entry and safe recovery." },
          { code: "AI.XIII.B.K3", category: "K", description: "Factors affecting VMC and how VMC differs from stall speed VS." },
          { code: "AI.XIII.B.K4", category: "K", description: "VMC red line VYSE blue line and safe single-engine speed VSSE." },
          { code: "AI.XIII.B.K5", category: "K", description: "Cause of loss of directional control at airspeeds below VMC." },
          { code: "AI.XIII.B.K6", category: "K", description: "Common errors related to this Task." },
          { code: "AI.XIII.B.R1", category: "R", description: "Configuring the airplane." },
          { code: "AI.XIII.B.R2", category: "R", description: "Maneuvering with one engine inoperative." },
          { code: "AI.XIII.B.R3", category: "R", description: "Distractions task prioritization loss of situational awareness or disorientation." },
          { code: "AI.XIII.B.S1", category: "S", description: "Configure the airplane in accordance with manufacturer's recommendations at VSSE or VYSE as appropriate with landing gear retracted flaps set for takeoff cowl flaps set for takeoff trim set for takeoff propellers set for high RPM power on critical engine reduced to idle and propeller windmilling and power on operating engine set to takeoff or maximum available power." },
          { code: "AI.XIII.B.S2", category: "S", description: "Establish a single-engine climb attitude with airspeed at approximately 10 knots above VSSE." },
          { code: "AI.XIII.B.S3", category: "S", description: "Establish a bank angle not to exceed 5 degrees toward the operating engine as required for best performance and controllability." },
          { code: "AI.XIII.B.S4", category: "S", description: "Increase pitch attitude slowly to reduce airspeed at approximately 1 knot per second while applying increased rudder pressure as needed to maintain directional control." },
          { code: "AI.XIII.B.S5", category: "S", description: "Recognize and recover at the first indication of loss of directional control stall warning or buffet." },
          { code: "AI.XIII.B.S6", category: "S", description: "Recover promptly by simultaneously reducing power sufficiently on the operating engine decreasing angle of attack as necessary to regain airspeed and directional control without adding power on the simulated failed engine." },
          { code: "AI.XIII.B.S7", category: "S", description: "Recover within 20 degrees of entry heading." },
          { code: "AI.XIII.B.S8", category: "S", description: "Advance power smoothly on the operating engine and accelerate to VSSE or VYSE plus or minus 5 knots during recovery." },
          { code: "AI.XIII.B.S9", category: "S", description: "Analyze and correct common errors related to this Task." }
        ]
      },
      {
        name: "Demonstration of Effects of Various Airspeeds and Configurations during Engine Inoperative Performance (AMEL, AMES)",
        code: "AI.XIII.C",
        references: "FAA-H-8083-2, FAA-H-8083-3, FAA-H-8083-9, FAA-H-8083-25; FAA-P-8740-66; POH/AFM",
        objective: "To determine the applicant understands the effects of various airspeeds and configurations during engine inoperative performance, can apply that knowledge, manage associated risks, demonstrate appropriate skills, and provide effective instruction.",
        stds: [
          { code: "AI.XIII.C.K1", category: "K", description: "Purpose for and elements of demonstration of effects of various airspeeds and configurations during engine inoperative performance." },
          { code: "AI.XIII.C.K2", category: "K", description: "Selection of appropriate altitude for the demonstration." },
          { code: "AI.XIII.C.K3", category: "K", description: "Proper entry procedure including pitch attitude bank attitude and airspeed." },
          { code: "AI.XIII.C.K4", category: "K", description: "Effects on performance of airspeed changes at above and below VYSE." },
          { code: "AI.XIII.C.K5", category: "K", description: "Effects on performance of various configurations including landing gear extended wing flaps extended landing gear and wing flaps extended and windmilling propeller on the inoperative engine." },
          { code: "AI.XIII.C.K6", category: "K", description: "Airspeed control throughout the demonstration." },
          { code: "AI.XIII.C.K7", category: "K", description: "Smooth control technique and coordination throughout the demonstration." },
          { code: "AI.XIII.C.K8", category: "K", description: "Common errors related to this Task." },
          { code: "AI.XIII.C.R1", category: "R", description: "Altitude selection." },
          { code: "AI.XIII.C.R2", category: "R", description: "Entry and recovery procedures." },
          { code: "AI.XIII.C.R3", category: "R", description: "Loss of control or stall." },
          { code: "AI.XIII.C.R4", category: "R", description: "Configuring the airplane." },
          { code: "AI.XIII.C.R5", category: "R", description: "Collision hazards." },
          { code: "AI.XIII.C.R6", category: "R", description: "Distractions task prioritization loss of situational awareness or disorientation." },
          { code: "AI.XIII.C.S1", category: "S", description: "Demonstrate describe and explain effects of various airspeeds and configurations during engine inoperative performance." },
          { code: "AI.XIII.C.S2", category: "S", description: "Demonstrate smooth control inputs when transitioning between various airspeeds and configurations including landing gear extended wing flaps extended landing gear and wing flaps extended and windmilling propeller on the inoperative engine." },
          { code: "AI.XIII.C.S3", category: "S", description: "Maintain appropriate airspeed attitude and altitude combinations for the various configurations." },
          { code: "AI.XIII.C.S4", category: "S", description: "Return to normal cruise flight at the altitude and heading specified by the evaluator." },
          { code: "AI.XIII.C.S5", category: "S", description: "Analyze and correct common errors related to this Task." }
        ]
      }
    ]
  }
];
